### ISSUE TITLE
Fix NullSite condition

### ISSUE THREAD

**Issue by ayacoo** [ayacoo/redirect_tab#25]
https://github.com/ayacoo/redirect_tab/commit/f09b6bd3132ca22af81ab7b8f91b1378dd905754#r132135605

**Comment by schugabe** [comment]
imho this has nothing to do with the nullsite condition. The redirects demand supports pagination and the first parameter is the page number of that pagination and not the page uid.

**Comment by ayacoo** [comment]
Yes, exactly. The condition is OK, but the "page" parameter for the pagination. I'm currently working on a mini release where I'll fix this and add the pagination.
