### ISSUE TITLE
Exception if a page has no valid site configuration

### ISSUE THREAD

**Issue by josefglatz** [ayacoo/redirect_tab#27]
If you add a page which is not part of a TYPO3 site config an exception is thrown (TYPO3 12.4.14)

![image](https://github.com/ayacoo/redirect_tab/assets/2861556/c97da89e-4f54-437b-b8d4-92397aa0e4fc)

**Comment by ayacoo** [comment]
Thanks for your hint. The bug has been fixed in version 3.1.3.
