### ISSUE TITLE
Release new version which is compatible with PHP 8.3

### ISSUE THREAD

**Issue by simonschaufi** [ayacoo/redirect_tab#30]
The current release 3.1.3 is not compatible with PHP 8.3

**Comment by ayacoo** [comment]
This is already planned for the next version, but must be made up for in the 3.x branch / TYPO3 v12 . Thanks for the hint :-)

**Comment by ayacoo** [comment]
The version 3.1.4 now supports PHP 8.3. Thanks again for the hint!
